// lib/repositories/shopping_list_repository.dart
import 'package:drift/drift.dart';
import '../database.dart';

class ShoppingListRepository extends DatabaseAccessor<AppDatabase> {
  final AppDatabase db;
  ShoppingListRepository(this.db) : super(db);

  @override
  AppDatabase get attachedDatabase => db;

  Future<List<ShoppingListData>> getShoppingList() {
    return db.getShoppingList();
  }

  Future<List<ShoppingListData>> getAllShoppingList() {
    return select(db.shoppingList).get();
  }

  Future<int> addToShoppingList({
    int? ingredientId,
    String? customName,
    required double quantity,
    required String unit,
    bool isAutoGenerated = false,
    bool isChecked = false,
  }) {
    final companion = ShoppingListCompanion(
      ingredientId: Value(ingredientId),
      customName: Value(customName),
      quantity: Value(quantity),
      unit: Value(unit),
      isAutoGenerated: Value(isAutoGenerated),
      isChecked: Value(isChecked),
    );
    return into(db.shoppingList).insert(companion);
  }

  Future<int> toggleChecked(int id, bool isChecked) {
    return (update(db.shoppingList)..where((t) => t.id.equals(id)))
        .write(ShoppingListCompanion(isChecked: Value(isChecked)));
  }

  Future<int> deleteItem(int id) {
    return (delete(db.shoppingList)..where((t) => t.id.equals(id))).go();
  }

  Future<void> clearAutoGenerated() async {
    await (delete(db.shoppingList)..where((t) => t.isAutoGenerated.equals(true))).go();
  }

  Future<void> clearChecked() async {
    await (delete(db.shoppingList)..where((t) => t.isChecked.equals(true))).go();
  }

  Future<void> clearAll() async {
    await delete(db.shoppingList).go();
  }
}