// lib/models/shopping_list_firestore.dart
import 'package:cloud_firestore/cloud_firestore.dart';

enum ShoppingVisibility {
  local,    // Liste locale synchronisée dans le cloud
  private,  // Liste privée cloud
  group,    // Liste partagée en groupe
}

enum ShoppingStatus {
  pending,    // À acheter
  completed,  // Dans le panier (prêt à stocker)
  stored,     // Déjà stocké
}

class ShoppingListFirestore {
  final String id;
  final String ownerId;
  final String? ingredientId;
  final String? ingredientName;
  final String? customName;
  final double quantity;
  final String unit;
  final String? category; // Catégorie pour le tri

  final ShoppingStatus status;
  final String? storageLocation; // frigo, placard, congélateur (quand status = completed)

  final bool isAutoGenerated;
  final ShoppingVisibility visibility;
  final String? groupId;

  // Valeurs nutritionnelles (optionnelles)
  final double? caloriesPer100g;
  final double? proteinsPer100g;
  final double? fatsPer100g;
  final double? carbsPer100g;
  final double? fibersPer100g;
  final double? densityGPerMl;
  final double? avgWeightPerUnitG;

  final DateTime createdAt;
  final DateTime updatedAt;

  ShoppingListFirestore({
    required this.id,
    required this.ownerId,
    this.ingredientId,
    this.ingredientName,
    this.customName,
    required this.quantity,
    required this.unit,
    this.category,
    required this.status,
    this.storageLocation,
    required this.isAutoGenerated,
    required this.visibility,
    this.groupId,
    this.caloriesPer100g,
    this.proteinsPer100g,
    this.fatsPer100g,
    this.carbsPer100g,
    this.fibersPer100g,
    this.densityGPerMl,
    this.avgWeightPerUnitG,
    required this.createdAt,
    required this.updatedAt,
  });

  factory ShoppingListFirestore.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;

    return ShoppingListFirestore(
      id: doc.id,
      ownerId: data['ownerId'] ?? '',
      ingredientId: data['ingredientId'],
      ingredientName: data['ingredientName'],
      customName: data['customName'],
      quantity: (data['quantity'] ?? 0).toDouble(),
      unit: data['unit'] ?? 'g',
      category: data['category'],
      status: _statusFromString(data['status'] ?? 'pending'),
      storageLocation: data['storageLocation'],
      isAutoGenerated: data['isAutoGenerated'] ?? false,
      visibility: data['visibility'] == 'group'
          ? ShoppingVisibility.group
          : data['visibility'] == 'local'
          ? ShoppingVisibility.local
          : ShoppingVisibility.private,
      groupId: data['groupId'],
      caloriesPer100g: data['caloriesPer100g']?.toDouble(),
      proteinsPer100g: data['proteinsPer100g']?.toDouble(),
      fatsPer100g: data['fatsPer100g']?.toDouble(),
      carbsPer100g: data['carbsPer100g']?.toDouble(),
      fibersPer100g: data['fibersPer100g']?.toDouble(),
      densityGPerMl: data['densityGPerMl']?.toDouble(),
      avgWeightPerUnitG: data['avgWeightPerUnitG']?.toDouble(),
      createdAt: (data['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
      updatedAt: (data['updatedAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
    );
  }

  Map<String, dynamic> toFirestore() {
    return {
      'ownerId': ownerId,
      'ingredientId': ingredientId,
      'ingredientName': ingredientName,
      'customName': customName,
      'quantity': quantity,
      'unit': unit,
      'category': category,
      'status': _statusToString(status),
      'storageLocation': storageLocation,
      'isAutoGenerated': isAutoGenerated,
      'visibility': visibility == ShoppingVisibility.group
          ? 'group'
          : visibility == ShoppingVisibility.local
          ? 'local'
          : 'private',
      'groupId': groupId,
      'caloriesPer100g': caloriesPer100g,
      'proteinsPer100g': proteinsPer100g,
      'fatsPer100g': fatsPer100g,
      'carbsPer100g': carbsPer100g,
      'fibersPer100g': fibersPer100g,
      'densityGPerMl': densityGPerMl,
      'avgWeightPerUnitG': avgWeightPerUnitG,
      'createdAt': Timestamp.fromDate(createdAt),
      'updatedAt': Timestamp.fromDate(updatedAt),
    };
  }

  static ShoppingStatus _statusFromString(String status) {
    switch (status) {
      case 'completed':
        return ShoppingStatus.completed;
      case 'stored':
        return ShoppingStatus.stored;
      default:
        return ShoppingStatus.pending;
    }
  }

  static String _statusToString(ShoppingStatus status) {
    switch (status) {
      case ShoppingStatus.completed:
        return 'completed';
      case ShoppingStatus.stored:
        return 'stored';
      default:
        return 'pending';
    }
  }

  String get displayName => ingredientName ?? customName ?? 'Article';

  String get statusLabel {
    switch (status) {
      case ShoppingStatus.pending:
        return 'À acheter';
      case ShoppingStatus.completed:
        return 'Acheté';
      case ShoppingStatus.stored:
        return 'Stocké';
    }
  }

  String get visibilityLabel {
    switch (visibility) {
      case ShoppingVisibility.local:
        return 'Local';
      case ShoppingVisibility.private:
        return 'Privé';
      case ShoppingVisibility.group:
        return 'Groupe';
    }
  }

  bool canEdit(String userId) {
    if (ownerId == userId) return true;
    if (visibility == ShoppingVisibility.group) return true;
    return false;
  }

  ShoppingListFirestore copyWith({
    String? id,
    String? ownerId,
    String? ingredientId,
    String? ingredientName,
    String? customName,
    double? quantity,
    String? unit,
    String? category,
    ShoppingStatus? status,
    String? storageLocation,
    bool? isAutoGenerated,
    ShoppingVisibility? visibility,
    String? groupId,
    double? caloriesPer100g,
    double? proteinsPer100g,
    double? fatsPer100g,
    double? carbsPer100g,
    double? fibersPer100g,
    double? densityGPerMl,
    double? avgWeightPerUnitG,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return ShoppingListFirestore(
      id: id ?? this.id,
      ownerId: ownerId ?? this.ownerId,
      ingredientId: ingredientId ?? this.ingredientId,
      ingredientName: ingredientName ?? this.ingredientName,
      customName: customName ?? this.customName,
      quantity: quantity ?? this.quantity,
      unit: unit ?? this.unit,
      category: category ?? this.category,
      status: status ?? this.status,
      storageLocation: storageLocation ?? this.storageLocation,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      visibility: visibility ?? this.visibility,
      groupId: groupId ?? this.groupId,
      caloriesPer100g: caloriesPer100g ?? this.caloriesPer100g,
      proteinsPer100g: proteinsPer100g ?? this.proteinsPer100g,
      fatsPer100g: fatsPer100g ?? this.fatsPer100g,
      carbsPer100g: carbsPer100g ?? this.carbsPer100g,
      fibersPer100g: fibersPer100g ?? this.fibersPer100g,
      densityGPerMl: densityGPerMl ?? this.densityGPerMl,
      avgWeightPerUnitG: avgWeightPerUnitG ?? this.avgWeightPerUnitG,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}