// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7dH-SPcW4CrYfpsmpD9UKlQOUkKZFy4w',
    appId: '1:43747636274:web:beea4f5c50b93f8596b82b',
    messagingSenderId: '43747636274',
    projectId: 'stoki-1d980',
    authDomain: 'stoki-1d980.firebaseapp.com',
    storageBucket: 'stoki-1d980.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkguF7ZkG0fYu_ol1HjbJ_oTyEAsSKcxM',
    appId: '1:43747636274:android:b0b949a4a32099e096b82b',
    messagingSenderId: '43747636274',
    projectId: 'stoki-1d980',
    storageBucket: 'stoki-1d980.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6IJYpoZc7JzvyRFL1oHy9ohSjQGsozoE',
    appId: '1:43747636274:ios:5bd7d70fe0d3928196b82b',
    messagingSenderId: '43747636274',
    projectId: 'stoki-1d980',
    storageBucket: 'stoki-1d980.firebasestorage.app',
    iosClientId: '43747636274-um3gain8envdjk5hfnm8ldpk1bvcauer.apps.googleusercontent.com',
    iosBundleId: 'com.example.stoki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6IJYpoZc7JzvyRFL1oHy9ohSjQGsozoE',
    appId: '1:43747636274:ios:5bd7d70fe0d3928196b82b',
    messagingSenderId: '43747636274',
    projectId: 'stoki-1d980',
    storageBucket: 'stoki-1d980.firebasestorage.app',
    iosClientId: '43747636274-um3gain8envdjk5hfnm8ldpk1bvcauer.apps.googleusercontent.com',
    iosBundleId: 'com.example.stoki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7dH-SPcW4CrYfpsmpD9UKlQOUkKZFy4w',
    appId: '1:43747636274:web:39b59842e9ea6fac96b82b',
    messagingSenderId: '43747636274',
    projectId: 'stoki-1d980',
    authDomain: 'stoki-1d980.firebaseapp.com',
    storageBucket: 'stoki-1d980.firebasestorage.app',
  );
}
